version: '3.3'
services:
  ui:
    command: ["puma", "--debug", "-w", "2"]
    volumes:
      - /app/ui:/app
  post:
    volumes:
      - /app/post-py:/app
  comment:
    command: ["puma","--debug","-w","2"]
    volumes:
      - /app/comment:/app
